GOOGLE_CLIENT_ID: 474960455868-ch47fhr7ifs7vnmbadqs4e82hf6p3sgg.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 1lDcBNWAH3yY8Q73Jpu8tlv4
GOOGLE_API_KEY: AIzaSyCMdsY3lGx8E4Hm48R_1ALG0AVMgftlaMk
ACCESS_KEY_ID: AKIAISLSJ37X47W7QD5A
SECRET_ACCESS_KEY: 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
database_password: 0522Lucknow
google_geocoder_key: AIzaSyBjXIvalZa0ca6ToiItrQgZho5ChFbLL-0
stripe_api_key: sk_test_HAZ0kgV2jSI1JVS7knhg1Jnl
stripe_publishable_key: pk_test_OymkohZ06VsKAdnEA9qSMAPG
rake_secret: f639786907201015252f972918423e8730e2bac3d9befc08fbe0e79b433e606df02e5b0b34b706cd9485a13756f1ea8aeb69b1cb29631bed47ec218d12acffa5
heed_user_key: b8207c28fb4c439cad73b2cf7a772241

production:
 stripe_api_key: sk_live_XyNaVDpTx1dI8I9e0LiEs0Nn
 stripe_publishable_key: pk_live_Wygr0osInPGWGBC13QkUrWVk
 GOOGLE_CLIENT_ID: 474960455868-ch47fhr7ifs7vnmbadqs4e82hf6p3sgg.apps.googleusercontent.com
 GOOGLE_CLIENT_SECRET: 1lDcBNWAH3yY8Q73Jpu8tlv4
 GOOGLE_API_KEY: AIzaSyCMdsY3lGx8E4Hm48R_1ALG0AVMgftlaMk
 ACCESS_KEY_ID: AKIAISLSJ37X47W7QD5A
 SECRET_ACCESS_KEY: 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
 database_password: 0522LucknowIndia
 rake_secret: f639786907201015252f972918423e8730e2bac3d9befc08fbe0e79b433e606df02e5b0b34b706cd9485a13756f1ea8aeb69b1cb29631bed47ec218d12acffa5
 heed_user_key: b8207c28fb4c439cad73b2cf7a772241

staging:
 stripe_api_key: sk_test_HAZ0kgV2jSI1JVS7knhg1Jnl
 stripe_publishable_key: pk_test_OymkohZ06VsKAdnEA9qSMAPG
 GOOGLE_CLIENT_ID: 474960455868-ch47fhr7ifs7vnmbadqs4e82hf6p3sgg.apps.googleusercontent.com
 GOOGLE_CLIENT_SECRET: 1lDcBNWAH3yY8Q73Jpu8tlv4
 GOOGLE_API_KEY: AIzaSyCMdsY3lGx8E4Hm48R_1ALG0AVMgftlaMk
 ACCESS_KEY_ID: AKIAISLSJ37X47W7QD5A
 SECRET_ACCESS_KEY: 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
 database_password: 0522LucknowIndia
 rake_secret: f639786907201015252f972918423e8730e2bac3d9befc08fbe0e79b433e606df02e5b0b34b706cd9485a13756f1ea8aeb69b1cb29631bed47ec218d12acffa5
 heed_user_key: b8207c28fb4c439cad73b2cf7a772241
