default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: vi_development
  username: raaaaj5000
  password: ENV["database_password"]

test:
  <<: *default
  database: vi_test
  username: raaaaj5000
  password: ENV["database_password"]

staging:
  <<: *default
  database: vi_staging
  username: raaaaj5000
  password: ENV["database_password"]

production:
  <<: *default
  database: vi_production
  username: raaaaj5000
  password: ENV["database_password"]