set :domain_name, '.staging.vivieu.com'
set :deploy_stage, 'staging'
set :deploy_location, '/var/www/staging.vivieu.com'
set :puma_process_name, 'staging'
set :shared_path_app, '/var/www/staging.vivieu.com/shared'